import { LearningMode, LearningModeInfo } from '../types';

export const LEARNING_MODES: LearningModeInfo[] = [
  {
    id: 'explain',
    name: 'Explain Mode',
    tagline: 'Structured concept breakdown',
    iconName: 'BookOpen',
    description: 'Master a concept from core fundamentals up to real-world applications with structured reasoning.',
    samplePrompt: 'Explain how Photosynthesis works, starting with the light reactions.',
    category: 'Understand',
  },
  {
    id: 'simplify',
    name: 'Simplify Mode',
    tagline: 'Intuitive "ELI10" & analogies',
    iconName: 'Sparkles',
    description: 'Break complex ideas down into simple, vivid language and everyday analogies without sacrificing accuracy.',
    samplePrompt: 'Simplify the concept of Quantum Entanglement using an everyday analogy.',
    category: 'Understand',
  },
  {
    id: 'deep_dive',
    name: 'Deep Dive Mode',
    tagline: 'Formal theory & mechanics',
    iconName: 'Compass',
    description: 'Rigorous technical explanation with mathematical foundations, nuances, proofs, and edge cases.',
    samplePrompt: 'Provide a deep dive into Transformer Self-Attention mechanics with matrix formulations.',
    category: 'Understand',
  },
  {
    id: 'step_by_step',
    name: 'Step-by-Step Mode',
    tagline: 'Interactive micro-step guidance',
    iconName: 'GitCommit',
    description: 'Work through difficult problems one micro-step at a time. EduGenie guides you, asking you to solve each step.',
    samplePrompt: 'Guide me step-by-step to integrate ∫ x · e^(2x) dx using integration by parts.',
    category: 'Practice',
  },
  {
    id: 'homework',
    name: 'Homework Assistance',
    tagline: 'Ethical learning & error review',
    iconName: 'FileText',
    description: 'Get guided method explanations without blind copying, or paste your work for constructive, non-judgmental review.',
    samplePrompt: 'Here is my attempt at solving Newton’s 2nd Law on an inclined plane. Can you review where I went wrong?',
    category: 'Practice',
  },
  {
    id: 'quiz',
    name: 'Quiz Mode',
    tagline: 'Dynamic active recall tests',
    iconName: 'HelpCircle',
    description: 'Interactive question-by-question testing with adaptive difficulty, instant hints, and detailed explanations.',
    samplePrompt: 'Quiz me on Mendelian Genetics and Punnett squares at high school level.',
    category: 'Practice',
  },
  {
    id: 'flashcards',
    name: 'Flashcard Mode',
    tagline: 'Spaced repetition decks',
    iconName: 'Layers',
    description: 'Create concise, high-yield flashcard decks with key terms, mnemonics, and practical examples.',
    samplePrompt: 'Generate a flashcard deck for Organic Chemistry functional groups and reactions.',
    category: 'Practice',
  },
  {
    id: 'teach_back',
    name: 'Teach-Back Mode',
    tagline: 'Feynman Technique arena',
    iconName: 'Award',
    description: 'Explain the concept in your own words. EduGenie evaluates your understanding, spots gaps, and clarifies misconceptions.',
    samplePrompt: 'I want to teach you the Law of Supply and Demand in my own words.',
    category: 'Evaluate',
  },
  {
    id: 'exam',
    name: 'Exam Mode',
    tagline: 'Mock tests with rubrics',
    iconName: 'CheckCircle',
    description: 'Simulate realistic exam papers (MCQ, short, and long questions) complete with mark schemes and rubrics.',
    samplePrompt: 'Generate a 20-mark mock exam paper on World War II causes and diplomacy.',
    category: 'Evaluate',
  },
  {
    id: 'revision',
    name: 'Revision Mode',
    tagline: 'High-yield cheat sheets',
    iconName: 'Zap',
    description: 'Quick pre-exam review: extract critical formulas, core definitions, and top pitfalls into a crisp digest.',
    samplePrompt: 'Give me a rapid revision cheat sheet for Calculus Differentiation Rules.',
    category: 'Organize',
  },
  {
    id: 'summarize',
    name: 'Summarize Mode',
    tagline: 'Structured notes converter',
    iconName: 'ListOrdered',
    description: 'Transform lengthy textbook chapters, lecture notes, or research papers into organized study notes.',
    samplePrompt: 'Summarize the stages of Mitosis and Meiosis in a clean comparative table format.',
    category: 'Organize',
  },
  {
    id: 'study_plan',
    name: 'Study Plan Mode',
    tagline: 'Personalized spaced schedules',
    iconName: 'Calendar',
    description: 'Build realistic, time-budgeted study schedules with active recall, revision buffers, and rest breaks.',
    samplePrompt: 'Create a 14-day study plan to prepare for AP Physics Mechanics with 1.5 hours daily.',
    category: 'Organize',
  },
];

export const DEFAULT_PROFILE = {
  name: 'Alex',
  grade: 'High School' as const,
  subject: 'Mathematics' as const,
  difficulty: 'Intermediate' as const,
  objective: 'Concept Mastery' as const,
  availableTime: '45 mins daily',
  focusTopic: 'Calculus & Derivatives',
};
